'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const { runAgentTaskToReview } = require('../lib/agent-task-to-review-runner');
const runtimeAgentCi = require('..');

assert.equal(runtimeAgentCi.runAgentTaskToReview, runAgentTaskToReview);

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'homeboy-agent-task-to-review.'));
try {
  const workspace = path.join(tmp, 'repo');
  fs.mkdirSync(workspace, { recursive: true });
  run('git', ['init'], workspace);
  run('git', ['config', 'user.name', 'Fixture'], workspace);
  run('git', ['config', 'user.email', 'fixture@example.test'], workspace);
  fs.writeFileSync(path.join(workspace, 'README.md'), '# Fixture\n');
  run('git', ['add', 'README.md'], workspace);
  run('git', ['commit', '-m', 'Initial fixture'], workspace);

  const executorPath = path.join(tmp, 'local-shell-executor.sh');
  fs.writeFileSync(executorPath, `#!/bin/sh
set -eu
mkdir -p "$HOMEBOY_FIXTURE_WORKSPACE/docs"
printf '# Generated by fixture\n' > "$HOMEBOY_FIXTURE_WORKSPACE/docs/generated.md"
cat >/dev/null
printf '%s\n' '{"schema":"homeboy/agent-task-outcome/v1","task_id":"fixture-review","status":"succeeded","summary":"Fixture local-shell executor wrote a file.","metadata":{"results":{"scenarios":[{"id":"fixture-review","metrics":{"generic_agent_task_executor_mean":1},"metadata":{"job_status":"completed","success_status":"changes_ready","completion_outcome":"done","completion_outcome_satisfied":true}}]}}}'
`);
  fs.chmodSync(executorPath, 0o755);

  const result = runAgentTaskToReview({
    runtime: {
      id: 'local-shell-fixture',
      executor: {
        backend: 'local-shell',
        invocation: {
          command: executorPath,
          cwd: workspace,
          env: { HOMEBOY_FIXTURE_WORKSPACE: workspace },
          stdin: 'request_json',
          stdout: 'outcome_json',
        },
      },
    },
    plan: {
      workload_id: 'fixture-review',
      target_repo: 'Extra-Chill/homeboy-extensions',
      component_path: workspace,
      runtime_profile: 'local-shell',
      runtime_profiles: { 'local-shell': { id: 'local-shell', runtime_task_ability: 'fixture/run' } },
      provider: 'local-shell',
      model: 'fixture',
      agent_slug: 'fixture-agent',
      success_requires_pr: true,
      success_completion_outcomes: ['done'],
      writable_paths: ['docs/**'],
      verification_commands: [{ command: 'test -f docs/generated.md', description: 'generated file exists' }],
      runner_workspace: { branch: 'agent-artifacts/{agent_slug}-{run_id}', from: 'origin/main' },
    },
    validationPolicy: { success_completion_outcomes: ['done'] },
    hooks: {
      env: { GITHUB_RUN_ID: 'fixture-run', HOMEBOY_HOST_LIFECYCLE_DRY_RUN: '1' },
      tmpdir: tmp,
    },
  });

  assert.equal(result.schema, 'homeboy/agent-task-to-review-result/v1');
  assert.equal(result.status, 'succeeded');
  assert.equal(result.terminal_status, 'green');
  assert.equal(result.runtime_result.outcome.status, 'succeeded');
  assert.equal(result.verification_result.verification.success, true);
  assert.equal(result.publication_result.dry_run, true);
  assert.equal(result.publication_result.opened, false);
  assert.equal(result.publication_result.publication_evidence_ref.head, 'agent-artifacts/fixture-agent-fixture-run');
  assert.equal(result.production_proof.status, 'succeeded');
  assert.equal(result.controller_proof_validation.valid, true);
  assert.equal(result.results.scenarios[0].metadata.controller_loop_proof_validation.valid, true);
  assert.deepEqual(result.artifacts.changed_files, ['docs/generated.md']);
  assert.equal(result.gate_result.success, true);
  assert.equal(fs.readFileSync(path.join(workspace, 'docs/generated.md'), 'utf8'), '# Generated by fixture\n');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error((result.stderr || result.stdout || `${command} ${args.join(' ')} failed`).trim());
  }
  return result;
}

process.stdout.write('Agent task to review runner checks passed\n');
