'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { CONFIG_ENV, MARKER, PROVIDER_ID, SCHEMA, finalizeOwnershipMarker, handleRequest, writeOwnershipMarker } = require('../lib/opencode-external-storage-retention');

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'opencode-retention-'));
try {
	const temp = path.join(root, 'interactive-temp');
	const data = path.join(root, 'durable-data');
	const scratch = path.join(temp, 'terminal-scratch');
	const active = path.join(temp, 'active-scratch');
	const forged = path.join(temp, 'forged');
	const unknown = path.join(temp, 'mixed-version');
	const external = path.join(root, 'outside');
	const database = path.join(data, 'named-runtime.db');
	for (const directory of [scratch, active, forged, unknown, external]) fs.mkdirSync(directory, { recursive: true });
	fs.mkdirSync(data, { recursive: true });
	fs.writeFileSync(path.join(scratch, 'payload'), '1234567');
	fs.writeFileSync(path.join(active, 'payload'), 'active');
	fs.writeFileSync(path.join(forged, 'payload'), 'forged');
	fs.writeFileSync(path.join(unknown, 'payload'), 'unknown');
	fs.writeFileSync(path.join(external, 'payload'), 'outside');
	fs.symlinkSync(external, path.join(temp, 'symlink'));
	fs.writeFileSync(database, '12345678901234567890');
	fs.writeFileSync(path.join(data, 'auth.json'), 'credential');
	fs.mkdirSync(path.join(data, 'snapshot'), { recursive: true });
	const command = path.join(root, 'opencode-fixture.cjs');
	const commandLog = path.join(root, 'native.log');
	fs.writeFileSync(command, `#!/usr/bin/env node
const fs = require('node:fs');
const args = process.argv.slice(2);
if (args.join(' ') === 'debug paths') process.stdout.write('data  ${data}\\ntmp  ${temp}\\n');
else if (args.join(' ') === 'db path') process.stdout.write('${database}\\n');
else if (args.join(' ') === 'session list --format json') process.stdout.write(JSON.stringify([{id:'ses_old', updated:Date.parse('2020-01-01T00:00:00Z'), directory:'${path.join(root, 'workspace')}'},{id:'ses_expired', updated:Date.parse('2020-01-01T00:00:00Z'), directory:'${path.join(root, 'expired-workspace')}'},{id:'ses_pinned', updated:Date.parse('2020-01-01T00:00:00Z'), pinned:true, directory:'${path.join(root, 'workspace')}'}]));
else { fs.appendFileSync('${commandLog}', args.join(' ') + '\\n'); if (process.env.FAIL_DELETE === '1' && args[0] === 'session') process.exit(1); if (process.env.FAIL_VACUUM === '1' && args[0] === 'db') process.exit(1); if (args[0] === 'db') fs.truncateSync('${database}', 5); }
`);
	fs.chmodSync(command, 0o755);
	const configPath = path.join(root, 'retention.json');
	fs.writeFileSync(configPath, JSON.stringify({ command, temp_roots: [temp], data_roots: [data] }));
	const state = path.join(root, 'private-state');
	const env = { ...process.env, [CONFIG_ENV]: configPath, XDG_STATE_HOME: state };
	const linkedState = path.join(root, 'linked-state');
	fs.symlinkSync(external, linkedState);
	assert.equal(writeOwnershipMarker(path.join(temp, 'forged'), { task_id: 'symlink-state', workspace: path.join(root, 'workspace') }, { ...env, XDG_STATE_HOME: linkedState }), false);
	assert.equal(writeOwnershipMarker(scratch, { task_id: 'task-terminal', workspace: path.join(root, 'workspace') }, env), true);
	assert.equal(finalizeOwnershipMarker(scratch, 'ses_old', env), true);
	assert.equal(writeOwnershipMarker(active, { task_id: 'task-active', workspace: path.join(root, 'active-workspace') }, env), true);
	fs.writeFileSync(path.join(forged, MARKER), JSON.stringify({ schema: 'homeboy/opencode-retention-marker/v1', id: 'scratch:forged', task_id: 'forged', active: false, signature: 'forged' }));
	const options = { env, now: Date.parse('2026-08-23T00:00:00Z') };
	const inventory = handleRequest({ schema: SCHEMA, operation: 'inventory' }, options);
	assert.equal(inventory.provider_id, PROVIDER_ID);
	assert.equal(inventory.roots.some((entry) => entry.path === path.dirname(database)), true);
	assert.equal(inventory.items.find((entry) => entry.id === 'scratch:task-active').active, true);
	assert.equal(inventory.items.find((entry) => entry.id === 'session:ses_old').referenced, true);
	assert.equal(inventory.items.find((entry) => entry.id === 'session:ses_expired').referenced, false);
	assert.equal(inventory.items.find((entry) => entry.id.startsWith('session-store:')).bytes, Buffer.byteLength('12345678901234567890'));
	assert.equal(inventory.items.find((entry) => entry.id === 'session:ses_expired').bytes, 0);
	assert.equal(inventory.items.find((entry) => entry.id === 'session:ses_pinned').referenced, true);
	assert.deepEqual(Object.fromEntries(['ownership_known', 'reconstructable', 'active', 'referenced'].map((key) => [key, inventory.items.find((entry) => entry.id === 'scratch:task-terminal')[key]])), { ownership_known: true, reconstructable: true, active: false, referenced: true });
	assert.equal(inventory.items.some((entry) => entry.id === 'scratch:forged'), false);
	assert.equal(inventory.items.some((entry) => entry.class === 'credential'), true);
	assert.equal(inventory.items.some((entry) => entry.class === 'pinned_export'), true);
	assert.ok(inventory.unknown_bytes >= Buffer.byteLength('unknown'));
	const target = (id) => { const value = inventory.items.find((entry) => entry.id === id); return { id, reclaim_token: value.reclaim_token }; };
	assert.equal(handleRequest({ schema: SCHEMA, operation: 'inventory' }, options).generation, inventory.generation);
	assert.equal(fs.statSync(path.join(state, 'homeboy', 'opencode-retention.key')).mode & 0o077, 0);
	assert.equal(fs.lstatSync(path.join(state, 'homeboy')).isSymbolicLink(), false);
	const receipt = handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: inventory.generation, reclaim_targets: [target('scratch:task-terminal'), target('session:ses_expired'), target('scratch:task-active'), target('session:ses_pinned')] }, options);
	assert.deepEqual(receipt.reclaimed_item_ids, ['session:ses_expired']);
	assert.equal(receipt.reclaimed_bytes, 15);
	assert.equal(fs.existsSync(scratch), true);
	assert.equal(fs.existsSync(active), true);
	assert.equal(fs.existsSync(database), true);
	assert.equal(fs.existsSync(path.join(data, 'auth.json')), true);
	assert.equal(fs.existsSync(path.join(data, 'snapshot')), true);
	assert.deepEqual(fs.readFileSync(commandLog, 'utf8').trim().split('\n'), ['session delete ses_expired', 'db VACUUM']);
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: inventory.generation, reclaim_targets: [target('scratch:task-active')] }, options), /stale/);
	const afterCompaction = handleRequest({ schema: SCHEMA, operation: 'inventory' }, options);
	const failedSession = afterCompaction.items.find((entry) => entry.id === 'session:ses_expired');
	const failedReceipt = handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: afterCompaction.generation, reclaim_targets: [{ id: failedSession.id, reclaim_token: failedSession.reclaim_token }] }, { ...options, env: { ...env, FAIL_DELETE: '1' } });
	assert.deepEqual(failedReceipt.reclaimed_item_ids, []);
	assert.equal(fs.existsSync(database), true);
	const compactionFailure = handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: afterCompaction.generation, reclaim_targets: [{ id: failedSession.id, reclaim_token: failedSession.reclaim_token }] }, { ...options, env: { ...env, FAIL_VACUUM: '1' } });
	assert.deepEqual(compactionFailure.reclaimed_item_ids, ['session:ses_expired']);
	const pending = handleRequest({ schema: SCHEMA, operation: 'inventory' }, options).items.find((entry) => entry.id.startsWith('compaction:'));
	assert.ok(pending);
	assert.deepEqual(handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: handleRequest({ schema: SCHEMA, operation: 'inventory' }, options).generation, reclaim_targets: [{ id: pending.id, reclaim_token: pending.reclaim_token }] }, options).reclaimed_item_ids, [pending.id]);
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'reclaim', generation: 'bad', reclaim_targets: Array.from({ length: 1001 }, () => ({ id: 'x', reclaim_token: 'x' })) }, options), /ceiling/);
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'inventory', extra: true }, options), /valid/);
	fs.writeFileSync(configPath, JSON.stringify({ command, temp_roots: [temp], data_roots: [temp] }));
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'inventory' }, options), /overlap/);
	fs.writeFileSync(configPath, JSON.stringify({ command, temp_roots: [temp], data_roots: [data], unexpected: true }));
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'inventory' }, options), /shape/);
	fs.writeFileSync(configPath, 'x'.repeat(256 * 1024 + 1));
	assert.throws(() => handleRequest({ schema: SCHEMA, operation: 'inventory' }, options), /ceiling/);
	const originalKill = process.kill;
	process.kill = () => { const error = new Error('denied'); error.code = 'EPERM'; throw error; };
	fs.writeFileSync(configPath, JSON.stringify({ command, temp_roots: [temp], data_roots: [data] }));
	assert.equal(handleRequest({ schema: SCHEMA, operation: 'inventory' }, options).items.find((entry) => entry.id === 'scratch:task-active').active, true);
	process.kill = originalKill;
	const script = path.join(__dirname, '..', 'scripts', 'agent', 'homeboy-opencode-external-storage-retention.cjs');
	const protocol = spawnSync(process.execPath, [script], { input: JSON.stringify({ schema: SCHEMA, operation: 'inventory' }), encoding: 'utf8', env });
	assert.equal(protocol.status, 0, protocol.stderr);
	assert.equal(JSON.parse(protocol.stdout).schema, SCHEMA);
} finally {
	fs.rmSync(root, { recursive: true, force: true });
}
