#!/usr/bin/env node

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import { join, resolve } from 'node:path';

const extension = resolve(import.meta.dirname, '..');
const script = join(extension, 'scripts/cloudflare-worker-deploy.mjs');
const root = mkdtempSync(join(os.tmpdir(), 'homeboy-cloudflare-test-')); const worker = join(root, 'worker'); const bin = join(root, 'bin'); const exists = join(root, 'exists'); const received = join(root, 'received'); mkdirSync(worker); mkdirSync(bin);
writeFileSync(join(worker, 'wrangler.jsonc'), '{\n  // Real Wrangler JSONC uses `binding` for R2 and `name` for Durable Objects.\n  "name": "example-worker",\n  "main": "src/**/*.mjs",\n  "documentation": "https://example.test/worker",\n  "rules": [{"globs": ["**/*.wasm"]}],\n  /* Bindings remain discoverable around block comments. */\n  "r2_buckets": [{"binding": "CACHE", "bucket_name": "cache"}],\n  "durable_objects": {"bindings": [{"name": "STATE", "class_name": "State"}]},\n}\n');
writeFileSync(join(bin, 'wrangler'), `#!/usr/bin/env node
const fs=require('fs'); const a=process.argv.slice(2); fs.appendFileSync(process.env.CALLS,JSON.stringify(a)+'\\n');
if(a[0]==='whoami') process.stdout.write(JSON.stringify({accounts:[{id:'account-example'}]}));
else if(a[0]==='deployments'){if(process.env.MISSING_WORKER==='1'&&!fs.existsSync(process.env.EXISTS)){process.stderr.write('This Worker does not exist [code: 10007]');process.exitCode=1;}else{const n=Number(fs.readFileSync(process.env.STATE,'utf8')); fs.writeFileSync(process.env.STATE,String(n+1)); const records=[{id:'deployment-old',created_on:'2026-01-01T00:00:00Z',versions:[{version_id:'version-old',percentage:100}]},{id:'deployment-new',created_on:'2026-01-02T00:00:00Z',versions:[{version_id:'version-new',percentage:100}]},{id:'deployment-durable',created_on:'2026-01-03T00:00:00Z',versions:[{version_id:'version-durable',percentage:100}]}]; const snapshots=[[records[0]],[records[0],records[1]],[records[0],records[1]],[...records]]; process.stdout.write(JSON.stringify(snapshots[Math.min(n,3)]));}}
else if(a[0]==='deploy'&&!a.includes('--dry-run')) fs.writeFileSync(process.env.EXISTS,'created');
else if(a[0]==='secret'){let v='';process.stdin.on('data',c=>v+=c);process.stdin.on('end',()=>{if(v!==process.env.SECRET_VALUE||process.env.FAIL_SECRET==='1')process.exitCode=2;});}
`); chmodSync(join(bin, 'wrangler'), 0o755);
writeFileSync(join(worker, 'provision.mjs'), `import { appendFileSync, writeFileSync } from 'node:fs'; let input=''; process.stdin.setEncoding('utf8'); process.stdin.on('data',chunk=>input+=chunk); process.stdin.on('end',()=>{writeFileSync(process.env.RECEIVED,input);appendFileSync(process.env.CALLS,JSON.stringify(['predeploy',process.env.TEST_PRIVATE_INPUT===undefined,process.env.TEST_SECRET===undefined,'sensitive-provider-output'])+'\\n');});`);
writeFileSync(join(worker, 'private-fixture'), 'file-private-input');
writeFileSync(join(root, 'private-input'), 'outside-repository'); mkdirSync(join(root, 'outside-cwd')); symlinkSync('../private-input', join(worker, 'linked-private-input')); symlinkSync('../outside-cwd', join(worker, 'linked-cwd'));
for (const command of [['init','-q'],['config','user.email','test@example.test'],['config','user.name','Test'],['add','.'],['commit','-qm','fixture']]) spawnSync('git', command, { cwd: worker });
const revision = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: worker, encoding: 'utf8' }).stdout.trim(); const calls = join(root, 'calls'); const state = join(root, 'state');
symlinkSync('worker', join(root, 'worker-link'));
const base = { schema:'homeboy/cloudflare-worker-deploy-contract/v1', repository:{worktree:worker,revision,ref:'fixture'}, wrangler:{binary:join(bin,'wrangler'),config:'wrangler.jsonc',config_ref:'wrangler.jsonc'}, target:{worker:'example-worker',account_id:'account-example'}, expected_bindings:['CACHE','STATE'], predeploy_commands:[{id:'provision-artifacts',executable:process.execPath,args:['provision.mjs'],stdin_secret_input:'operator-input'}], secret_inputs:[{id:'operator-input',env:'TEST_PRIVATE_INPUT'}], secrets:[{name:'API_TOKEN',env:'TEST_SECRET'}], gates:[], durability:{redeploy_same_revision:true}, timeout_ms:5000 };

const success = await run(base); assert.equal(success.status, 0, `${success.stdout}\n${success.stderr}`);
if (process.env.HOMEBOY_EXTENSION_RUN === '1') { assert.match(readFileSync(calls,'utf8'), /"secret","put","API_TOKEN"/); assert.equal(readFileSync(received,'utf8'),'operator-never-log-this-value'); rmSync(root,{recursive:true,force:true}); } else {
 const successful = outputResult(success.stdout);
assert.equal(successful.status, 'succeeded'); assert.deepEqual(successful.stages.map(({id})=>id), ['preflight','predeploy_commands','secret_provisioning','deploy','durability_redeploy']); assert.deepEqual(successful.stages[1].evidence.commands.map(({id,status})=>({id,status})), [{id:'provision-artifacts',status:'succeeded'}]); assert.deepEqual(successful.stages[0].evidence.required_secret_input_ids,['operator-input']); assert.equal(successful.deployments[0].prior_deployment.version_id, 'version-old'); assert.equal(successful.deployments[1].prior_deployment.version_id, 'version-new'); assert.equal(successful.deployments[0].deployed.version_id, 'version-new'); assert.equal(successful.deployments[1].deployed.version_id, 'version-durable'); assert.equal(readFileSync(received,'utf8'),'operator-never-log-this-value'); assert.equal(success.stdout.includes(worker), false); assert.equal(success.stdout.includes('never-log-this-value'), false); assert.equal(success.stdout.includes('operator-never-log-this-value'), false); assert.equal(success.stdout.includes('sensitive-provider-output'), false);
 const successCalls=readFileSync(calls,'utf8'); assert.equal((successCalls.match(/"secret","put"/g)||[]).length,1); assert.match(successCalls,/"predeploy",true,true/); assert.equal(successCalls.includes('never-log-this-value'),false); assert.equal(successCalls.includes('operator-never-log-this-value'),false);
 const dryRun = await run({...base,result_file:'dry-run-result.json'}, {}, ['--dry-run']); assert.equal(dryRun.status, 0, dryRun.stdout); const dryResult = outputResult(dryRun.stdout); assert.equal(dryResult.status, 'validated'); assert.equal(dryResult.mode, 'dry_run'); assert.equal(dryResult.stages[0].evidence.non_mutating, true); assert.deepEqual(dryResult.stages[0].evidence.gate_ids, []); assert.deepEqual(dryResult.stages[0].evidence.skipped, ['predeploy_commands', 'secret_provisioning', 'deployment', 'rollback', 'http_gates', 'result_file']); assert.equal(deploymentCalls(), 0); assert.equal(readFileSync(calls, 'utf8').includes('"secret"'), false); assert.equal(readFileSync(calls, 'utf8').includes('provision.mjs'), false); assert.equal(existsSync(join(worker, 'dry-run-result.json')), false);
 assert.equal(digest({wrangler:{config_ref:'wrangler.jsonc',config:'wrangler.jsonc',binary:'wrangler'},timeout_ms:120000,expected_bindings:['DATABASE']}),'13d79940b8c45f3df966296bf3080f254c281aaefd09b3308497ed94aede0486');
 const layeredPolicy={wrangler:base.wrangler,expected_bindings:base.expected_bindings,predeploy_commands:base.predeploy_commands,timeout_ms:base.timeout_ms}; const layered={schema:'homeboy/deployment-provider-payload/v1',policy:{value:layeredPolicy,reference:{component:'example-worker',path:'homeboy.json#/deployment_provider/policy',digest:digest(layeredPolicy)}},target:{target:base.target,secrets:base.secrets,secret_inputs:base.secret_inputs,gates:base.gates,durability:base.durability},source:{component:'example-worker',revision}};
 const layeredEnvironment={HOMEBOY_COMPONENT_ID:'example-worker',HOMEBOY_COMPONENT_PATH:worker}; const layeredApply=await run(layered,layeredEnvironment); assert.equal(layeredApply.status,0,layeredApply.stdout); const layeredResult=outputResult(layeredApply.stdout); assert.equal(layeredResult.schema,'homeboy/cloudflare-worker-deploy-result/v1'); assert.equal(layeredResult.source_revision,revision); assert.equal(layeredResult.source_ref,'example-worker'); assert.deepEqual(layeredResult.policy_reference,layered.policy.reference); assert.equal(layeredApply.stdout.includes(worker),false); assert.equal(layeredApply.stdout.includes('never-log-this-value'),false);
 const layeredDryRun=await run(layered,layeredEnvironment,['--dry-run']); assert.equal(layeredDryRun.status,0,layeredDryRun.stdout); assert.equal(outputResult(layeredDryRun.stdout).status,'validated'); assert.equal(deploymentCalls(),0);
 const mixedOwnership=structuredClone(layered); mixedOwnership.policy.value.target=base.target; const rejectedOwnership=await run(mixedOwnership,layeredEnvironment,['--dry-run']); assert.equal(rejectedOwnership.status,1); assert.match(JSON.parse(rejectedOwnership.stderr).error,/Unsupported layered policy field target/); assert.equal(deploymentCalls(),0);
 const tamperedPolicy=structuredClone(layered); tamperedPolicy.policy.value.timeout_ms+=1; const rejectedDigest=await run(tamperedPolicy,layeredEnvironment,['--dry-run']); assert.equal(rejectedDigest.status,1); assert.match(JSON.parse(rejectedDigest.stderr).error,/policy digest does not match/); assert.equal(deploymentCalls(),0);
 const mismatchedSource=await run({...layered,source:{...layered.source,component:'different-worker'}},layeredEnvironment,['--dry-run']); assert.equal(mismatchedSource.status,1); assert.match(JSON.parse(mismatchedSource.stderr).error,/does not match the execution context/); assert.equal(deploymentCalls(),0);
 const compatibleContract={...base,predeploy_commands:[{id:'provision-artifacts',executable:process.execPath,args:['-e','process.exit(0)']}]}; delete compatibleContract.secret_inputs; const compatible=await run(compatibleContract); assert.equal(compatible.status,0,compatible.stdout);
 const symlinkedWorktree=await run({...base,repository:{...base.repository,worktree:join(root,'worker-link')},secret_inputs:[{id:'operator-input',file:'private-fixture'}],predeploy_commands:[{...base.predeploy_commands[0],cwd:'.'}]}); assert.equal(symlinkedWorktree.status,0,symlinkedWorktree.stdout); assert.equal(readFileSync(received,'utf8'),'file-private-input'); assert.equal(symlinkedWorktree.stdout.includes('file-private-input'),false);
 const literalMismatch=await run({...base,repository:{...base.repository,revision:'0000000000000000000000000000000000000000'}}, {}, ['--dry-run']); assert.equal(literalMismatch.status,1); assert.equal(outputResult(literalMismatch.stdout).failure.code,'source_revision_mismatch');

 const portableWorker=join(root,'portable-worker'); mkdirSync(portableWorker); writeFileSync(join(portableWorker,'wrangler.jsonc'),readFileSync(join(worker,'wrangler.jsonc'))); const portablePath=join(portableWorker,'deploy-contract.json'); const portableContract={...base,repository:{worktree:'.',revision:'HEAD',ref:'fixture'},predeploy_commands:[],secret_inputs:[],secrets:[],durability:{redeploy_same_revision:false}}; writeFileSync(portablePath,JSON.stringify(portableContract)); for (const command of [['init','-q'],['config','user.email','test@example.test'],['config','user.name','Test'],['add','.'],['commit','-qm','portable fixture']]) spawnSync('git',command,{cwd:portableWorker}); const portableRevision=spawnSync('git',['rev-parse','HEAD'],{cwd:portableWorker,encoding:'utf8'}).stdout.trim(); const portable=await run(null,{},['--dry-run'],portablePath); assert.equal(portable.status,0,portable.stdout); const portableResult=outputResult(portable.stdout); assert.equal(portableResult.source_revision,portableRevision); assert.equal(portableResult.stages[0].evidence.source_revision,portableRevision); assert.equal(portable.stdout.includes(portableWorker),false); writeFileSync(join(portableWorker,'dirty'),'dirty'); const dirtyPortable=await run(null,{},['--dry-run'],portablePath); assert.equal(dirtyPortable.status,1); assert.equal(outputResult(dirtyPortable.stdout).failure.code,'source_not_clean'); rmSync(join(portableWorker,'dirty'));

 const retryServer=await listen([{status:500,body:'not-ready'},{status:200,body:'healthy'}]); try { const recovered=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${retryServer.port}/health`,expected_status:200,expected_text:'healthy',retry:{attempts:2,retry_delay_ms:0,transient_statuses:[500]}}],durability:{redeploy_same_revision:false}}); assert.equal(recovered.status,0, recovered.stdout); const result=outputResult(recovered.stdout); const attempts=result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts; assert.deepEqual(attempts.map(({attempt,status})=>({attempt,status})),[{attempt:1,status:500},{attempt:2,status:200}]); assert.ok(attempts.every(({elapsed_ms})=>Number.isInteger(elapsed_ms)&&elapsed_ms>=0)); assert.equal(JSON.stringify(attempts).includes('not-ready'),false); } finally { retryServer.server.close(); }

 const noPolicyServer=await listen([{status:500,body:'not-ready'},{status:200,body:'healthy'}]); try { const failed=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${noPolicyServer.port}/health`,expected_status:200}],durability:{redeploy_same_revision:false}}); assert.equal(failed.status,1); const result=outputResult(failed.stdout); assert.equal(result.failure.code,'http_gate_status_failed', failed.stdout); assert.deepEqual(result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts.map(({status})=>status),[500]); assert.equal(result.deployments[0].rollback.restored_version_id,'version-old'); assert.match(readFileSync(calls,'utf8'),/"rollback","version-old"/); } finally { noPolicyServer.server.close(); }

 const exhaustedServer=await listen([{status:500,body:'not-ready'},{status:500,body:'still-not-ready'}]); try { const failed=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${exhaustedServer.port}/health`,expected_status:200,retry:{attempts:2,retry_delay_ms:0,transient_statuses:[500]}}],durability:{redeploy_same_revision:false}}); assert.equal(failed.status,1); const result=outputResult(failed.stdout); assert.equal(result.failure.code,'http_gate_status_failed', failed.stdout); assert.deepEqual(result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts.map(({status})=>status),[500,500]); assert.equal(result.deployments[0].rollback.restored_version_id,'version-old'); } finally { exhaustedServer.server.close(); }

const failedSecret=await run({...base,durability:{redeploy_same_revision:false}}, {FAIL_SECRET:'1'}); assert.equal(failedSecret.status,1); const secretResult=outputResult(failedSecret.stdout); assert.equal(secretResult.failure.stage,'secret_provisioning'); assert.equal(secretResult.deployments.at(-1).rollback.restored_version_id,'version-old'); assert.match(readFileSync(calls,'utf8'),/"rollback","version-old"/);

 const invalidSecret=await run({...base,secrets:[{name:'../escape',env:'TEST_SECRET'}]}); assert.equal(invalidSecret.status,1); assert.equal(JSON.parse(invalidSecret.stderr).code,'invalid_contract');
 const duplicateInput=await run({...base,secret_inputs:[{id:'operator-input',env:'TEST_PRIVATE_INPUT'},{id:'operator-input',env:'TEST_PRIVATE_INPUT'}]}); assert.equal(duplicateInput.status,1); assert.equal(JSON.parse(duplicateInput.stderr).code,'invalid_contract');
 const unknownInput=await run({...base,predeploy_commands:[{...base.predeploy_commands[0],stdin_secret_input:'unknown'}]}); assert.equal(unknownInput.status,1); assert.equal(JSON.parse(unknownInput.stderr).code,'invalid_contract');
 const missingInput=await run({...base,secret_inputs:[{id:'operator-input',env:'MISSING_PRIVATE_INPUT'}]}); assert.equal(missingInput.status,1); assert.equal(outputResult(missingInput.stdout).failure.code,'secret_unavailable'); assert.equal(deploymentCalls(),0);
 const oversizedInput=await run(base,{TEST_PRIVATE_INPUT:'x'.repeat(65537)}); assert.equal(oversizedInput.status,1); assert.equal(outputResult(oversizedInput.stdout).failure.code,'secret_unavailable'); assert.equal(deploymentCalls(),0);
 const traversingInput=await run({...base,secret_inputs:[{id:'operator-input',file:'../private-input'}]}); assert.equal(traversingInput.status,1); assert.equal(outputResult(traversingInput.stdout).failure.code,'secret_unavailable'); assert.equal(traversingInput.stdout.includes(root),false); assert.equal(deploymentCalls(),0);
 const symlinkInput=await run({...base,secret_inputs:[{id:'operator-input',file:'linked-private-input'}]}); assert.equal(symlinkInput.status,1); assert.equal(outputResult(symlinkInput.stdout).failure.code,'secret_unavailable'); assert.equal(symlinkInput.stdout.includes(root),false); assert.equal(deploymentCalls(),0);
 const invalidRetry=await run({...base,gates:[{id:'health',url:'https://example.test/health',retry:{attempts:2,retry_delay_ms:0,transient_statuses:[]}}]}); assert.equal(invalidRetry.status,1); assert.equal(JSON.parse(invalidRetry.stderr).code,'invalid_contract');
 const missing=await run({...base,target:{...base.target,create_if_missing:true},durability:{redeploy_same_revision:false}},{MISSING_WORKER:'1'}); assert.equal(missing.status,0,missing.stdout); const missingResult=outputResult(missing.stdout); assert.deepEqual(missingResult.stages.map(({id})=>id),['preflight','predeploy_commands','bootstrap_create','secret_provisioning','deploy']); const missingCalls=readFileSync(calls,'utf8').trim().split('\n').map(JSON.parse); assert.ok(missingCalls.findIndex((args)=>args[0]==='deploy'&&!args.includes('--dry-run'))<missingCalls.findIndex((args)=>args[0]==='secret'));
 const missingUndeclared=await run({...base,durability:{redeploy_same_revision:false}},{MISSING_WORKER:'1'}); assert.equal(missingUndeclared.status,1); assert.equal(deploymentCalls(),0);
 const invalidShell=await run({...base,predeploy_commands:[{id:'unsafe',executable:'sh',args:['-c','exit 0']}]}); assert.equal(invalidShell.status,1); assert.equal(JSON.parse(invalidShell.stderr).code,'invalid_contract');
 const invalidCwd=await run({...base,predeploy_commands:[{id:'escape',executable:process.execPath,args:['provision.mjs'],cwd:'../outside'}]}); assert.equal(invalidCwd.status,1); assert.equal(outputResult(invalidCwd.stdout).failure.code,'invalid_contract'); assert.equal(deploymentCalls(),0);
 const symlinkCwd=await run({...base,predeploy_commands:[{id:'escape-link',executable:process.execPath,args:['provision.mjs'],cwd:'linked-cwd'}]}); assert.equal(symlinkCwd.status,1); assert.equal(outputResult(symlinkCwd.stdout).failure.code,'invalid_contract'); assert.equal(symlinkCwd.stdout.includes(root),false); assert.equal(deploymentCalls(),0);
 const failedPredeploy=await run({...base,predeploy_commands:[{id:'fails',executable:process.execPath,args:['-e','process.stderr.write("sensitive-provider-output");process.exit(2)']}]}); assert.equal(failedPredeploy.status,1); const predeployResult=outputResult(failedPredeploy.stdout); assert.equal(predeployResult.failure.code,'predeploy_command_failed'); assert.equal(failedPredeploy.stdout.includes('sensitive-provider-output'),false); assert.equal(deploymentCalls(),0);
 const failedPrivatePredeploy=await run({...base,predeploy_commands:[{id:'fails-private',executable:process.execPath,args:['-e',`let value='';process.stdin.on('data',chunk=>value+=chunk);process.stdin.on('end',()=>{process.stderr.write(value);process.exitCode=2;});`],stdin_secret_input:'operator-input'}]}); assert.equal(failedPrivatePredeploy.status,1); assert.equal(outputResult(failedPrivatePredeploy.stdout).failure.code,'predeploy_command_failed'); assert.equal(failedPrivatePredeploy.stdout.includes('operator-never-log-this-value'),false); assert.equal(failedPrivatePredeploy.stderr.includes('operator-never-log-this-value'),false); assert.equal(deploymentCalls(),0);
 const dirtyPredeploy=await run({...base,predeploy_commands:[{id:'changes-source',executable:process.execPath,args:['-e','require("fs").writeFileSync("generated-drift","changed")']}]}); assert.equal(dirtyPredeploy.status,1); assert.equal(outputResult(dirtyPredeploy.stdout).failure.code,'source_changed_by_predeploy'); assert.equal(deploymentCalls(),0); rmSync(join(worker,'generated-drift'));

writeFileSync(join(worker,'wrangler.jsonc'),'{"name":"example-worker","account_id":"another-account","r2_buckets":[{"binding":"CACHE"}],"durable_objects":{"bindings":[{"name":"STATE"}]}}'); spawnSync('git',['add','wrangler.jsonc'],{cwd:worker}); spawnSync('git',['commit','-qm','declare conflicting account'],{cwd:worker}); const conflictingRevision=spawnSync('git',['rev-parse','HEAD'],{cwd:worker,encoding:'utf8'}).stdout.trim(); const mismatch=await run({...base,repository:{...base.repository,revision:conflictingRevision}}); assert.equal(mismatch.status,1); assert.equal(outputResult(mismatch.stdout).failure.code,'account_target_mismatch');

rmSync(root,{recursive:true,force:true}); }
async function run(contract, environment={}, extraArgs=[], contractPath) { writeFileSync(calls,'');writeFileSync(state,'0');rmSync(exists,{force:true});rmSync(received,{force:true});const path=contractPath||join(root,'contract.json');if(contract)writeFileSync(path,JSON.stringify(contract));const throughHomeboy=process.env.HOMEBOY_EXTENSION_RUN==='1';const command=throughHomeboy?'homeboy':process.execPath;const args=throughHomeboy?['extension','run','cloudflare-workers','--',...extraArgs,'--contract',path]:[script,...extraArgs,'--contract',path];return new Promise((resolveRun,reject)=>{const child=spawn(command,args,{env:{...process.env,CALLS:calls,STATE:state,EXISTS:exists,RECEIVED:received,TEST_SECRET:'never-log-this-value',SECRET_VALUE:'never-log-this-value',TEST_PRIVATE_INPUT:'operator-never-log-this-value',...environment},stdio:['ignore','pipe','pipe']});let stdout='';let stderr='';child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.once('error',reject);child.once('close',status=>resolveRun({status,stdout,stderr}));}); }
function listen(responses) { let requests=0; const server=http.createServer((_q,res)=>{const response=responses[Math.min(requests++,responses.length-1)];res.statusCode=response.status;res.end(response.body);});return new Promise((resolveListen,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolveListen({server,port:server.address().port}));}); }
function outputResult(stdout) { const value=JSON.parse(stdout); return value.schema==='homeboy/command-result/v3' ? JSON.parse(value.data.output) : value; }
function deploymentCalls() { return readFileSync(calls,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse).filter((args)=>args[0]==='deploy'&&!args.includes('--dry-run')).length; }
function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`; if (value!==null&&typeof value==='object') return `{${Object.keys(value).sort().map((key)=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`; return JSON.stringify(value); }
function digest(value) { return createHash('sha256').update(canonicalJson(value)).digest('hex'); }
