#!/usr/bin/env node

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import { join, resolve } from 'node:path';

const extension = resolve(import.meta.dirname, '..');
const script = join(extension, 'scripts/cloudflare-worker-deploy.mjs');
const root = mkdtempSync(join(os.tmpdir(), 'homeboy-cloudflare-test-')); const worker = join(root, 'worker'); const bin = join(root, 'bin'); mkdirSync(worker); mkdirSync(bin);
writeFileSync(join(worker, 'wrangler.jsonc'), '{\n  // Real Wrangler JSONC uses `binding` for R2 and `name` for Durable Objects.\n  "name": "example-worker",\n  "r2_buckets": [{"binding": "CACHE", "bucket_name": "cache"}],\n  "durable_objects": {"bindings": [{"name": "STATE", "class_name": "State"}]},\n}\n');
writeFileSync(join(bin, 'wrangler'), `#!/usr/bin/env node
const fs=require('fs'); const a=process.argv.slice(2); fs.appendFileSync(process.env.CALLS,JSON.stringify(a)+'\\n');
if(a[0]==='whoami') process.stdout.write(JSON.stringify({accounts:[{id:'account-example'}]}));
else if(a[0]==='deployments'){const n=Number(fs.readFileSync(process.env.STATE,'utf8')); fs.writeFileSync(process.env.STATE,String(n+1)); const records=[{id:'deployment-old',created_on:'2026-01-01T00:00:00Z',versions:[{version_id:'version-old',percentage:100}]},{id:'deployment-new',created_on:'2026-01-02T00:00:00Z',versions:[{version_id:'version-new',percentage:100}]},{id:'deployment-durable',created_on:'2026-01-03T00:00:00Z',versions:[{version_id:'version-durable',percentage:100}]}]; const snapshots=[[records[0]],[records[0],records[1]],[records[0],records[1]],[...records]]; process.stdout.write(JSON.stringify(snapshots[Math.min(n,3)]));}
else if(a[0]==='secret'){let v='';process.stdin.on('data',c=>v+=c);process.stdin.on('end',()=>{if(v!==process.env.SECRET_VALUE||process.env.FAIL_SECRET==='1')process.exitCode=2;});}
`); chmodSync(join(bin, 'wrangler'), 0o755);
writeFileSync(join(worker, 'provision.mjs'), `import { appendFileSync } from 'node:fs'; appendFileSync(process.env.CALLS, JSON.stringify(['predeploy', 'sensitive-provider-output']) + '\\n');`);
for (const command of [['init','-q'],['config','user.email','test@example.test'],['config','user.name','Test'],['add','.'],['commit','-qm','fixture']]) spawnSync('git', command, { cwd: worker });
const revision = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: worker, encoding: 'utf8' }).stdout.trim(); const calls = join(root, 'calls'); const state = join(root, 'state');
const base = { schema:'homeboy/cloudflare-worker-deploy-contract/v1', repository:{worktree:worker,revision,ref:'fixture'}, wrangler:{binary:join(bin,'wrangler'),config:'wrangler.jsonc',config_ref:'wrangler.jsonc'}, target:{worker:'example-worker',account_id:'account-example'}, expected_bindings:['CACHE','STATE'], predeploy_commands:[{id:'provision-artifacts',executable:process.execPath,args:['provision.mjs']}], secrets:[{name:'API_TOKEN',env:'TEST_SECRET'}], gates:[], durability:{redeploy_same_revision:true}, timeout_ms:5000 };

const success = await run(base); assert.equal(success.status, 0, `${success.stdout}\n${success.stderr}`);
if (process.env.HOMEBOY_EXTENSION_RUN === '1') { assert.match(readFileSync(calls,'utf8'), /"secret","put","API_TOKEN"/); rmSync(root,{recursive:true,force:true}); } else {
const successful = outputResult(success.stdout);
assert.equal(successful.status, 'succeeded'); assert.deepEqual(successful.stages.map(({id})=>id), ['preflight','predeploy_commands','secret_provisioning','deploy','durability_redeploy']); assert.deepEqual(successful.stages[1].evidence.commands.map(({id,status})=>({id,status})), [{id:'provision-artifacts',status:'succeeded'}]); assert.equal(successful.deployments[0].prior_deployment.version_id, 'version-old'); assert.equal(successful.deployments[1].prior_deployment.version_id, 'version-new'); assert.equal(successful.deployments[0].deployed.version_id, 'version-new'); assert.equal(successful.deployments[1].deployed.version_id, 'version-durable'); assert.equal(success.stdout.includes(worker), false); assert.equal(success.stdout.includes('never-log-this-value'), false); assert.equal(success.stdout.includes('sensitive-provider-output'), false);
const successCalls=readFileSync(calls,'utf8'); assert.equal((successCalls.match(/"secret","put"/g)||[]).length,1); assert.equal(successCalls.includes('never-log-this-value'),false);

 const retryServer=await listen([{status:500,body:'not-ready'},{status:200,body:'healthy'}]); try { const recovered=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${retryServer.port}/health`,expected_status:200,expected_text:'healthy',retry:{attempts:2,retry_delay_ms:0,transient_statuses:[500]}}],durability:{redeploy_same_revision:false}}); assert.equal(recovered.status,0, recovered.stdout); const result=outputResult(recovered.stdout); const attempts=result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts; assert.deepEqual(attempts.map(({attempt,status})=>({attempt,status})),[{attempt:1,status:500},{attempt:2,status:200}]); assert.ok(attempts.every(({elapsed_ms})=>Number.isInteger(elapsed_ms)&&elapsed_ms>=0)); assert.equal(JSON.stringify(attempts).includes('not-ready'),false); } finally { retryServer.server.close(); }

 const noPolicyServer=await listen([{status:500,body:'not-ready'},{status:200,body:'healthy'}]); try { const failed=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${noPolicyServer.port}/health`,expected_status:200}],durability:{redeploy_same_revision:false}}); assert.equal(failed.status,1); const result=outputResult(failed.stdout); assert.equal(result.failure.code,'http_gate_status_failed', failed.stdout); assert.deepEqual(result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts.map(({status})=>status),[500]); assert.equal(result.deployments[0].rollback.restored_version_id,'version-old'); assert.match(readFileSync(calls,'utf8'),/"rollback","version-old"/); } finally { noPolicyServer.server.close(); }

 const exhaustedServer=await listen([{status:500,body:'not-ready'},{status:500,body:'still-not-ready'}]); try { const failed=await run({...base,gates:[{id:'health',url:`http://127.0.0.1:${exhaustedServer.port}/health`,expected_status:200,retry:{attempts:2,retry_delay_ms:0,transient_statuses:[500]}}],durability:{redeploy_same_revision:false}}); assert.equal(failed.status,1); const result=outputResult(failed.stdout); assert.equal(result.failure.code,'http_gate_status_failed', failed.stdout); assert.deepEqual(result.stages.find(({id})=>id==='deploy').evidence.gates[0].attempts.map(({status})=>status),[500,500]); assert.equal(result.deployments[0].rollback.restored_version_id,'version-old'); } finally { exhaustedServer.server.close(); }

const failedSecret=await run({...base,durability:{redeploy_same_revision:false}}, {FAIL_SECRET:'1'}); assert.equal(failedSecret.status,1); const secretResult=outputResult(failedSecret.stdout); assert.equal(secretResult.failure.stage,'secret_provisioning'); assert.equal(secretResult.deployments.at(-1).rollback.restored_version_id,'version-old'); assert.match(readFileSync(calls,'utf8'),/"rollback","version-old"/);

 const invalidSecret=await run({...base,secrets:[{name:'../escape',env:'TEST_SECRET'}]}); assert.equal(invalidSecret.status,1); assert.equal(JSON.parse(invalidSecret.stderr).code,'invalid_contract');
 const invalidRetry=await run({...base,gates:[{id:'health',url:'https://example.test/health',retry:{attempts:2,retry_delay_ms:0,transient_statuses:[]}}]}); assert.equal(invalidRetry.status,1); assert.equal(JSON.parse(invalidRetry.stderr).code,'invalid_contract');
 const invalidShell=await run({...base,predeploy_commands:[{id:'unsafe',executable:'sh',args:['-c','exit 0']}]}); assert.equal(invalidShell.status,1); assert.equal(JSON.parse(invalidShell.stderr).code,'invalid_contract');
 const invalidCwd=await run({...base,predeploy_commands:[{id:'escape',executable:process.execPath,args:['provision.mjs'],cwd:'../outside'}]}); assert.equal(invalidCwd.status,1); assert.equal(outputResult(invalidCwd.stdout).failure.code,'invalid_contract'); assert.equal(deploymentCalls(),0);
 const failedPredeploy=await run({...base,predeploy_commands:[{id:'fails',executable:process.execPath,args:['-e','process.stderr.write("sensitive-provider-output");process.exit(2)']}]}); assert.equal(failedPredeploy.status,1); const predeployResult=outputResult(failedPredeploy.stdout); assert.equal(predeployResult.failure.code,'predeploy_command_failed'); assert.equal(failedPredeploy.stdout.includes('sensitive-provider-output'),false); assert.equal(deploymentCalls(),0);

writeFileSync(join(worker,'wrangler.jsonc'),'{"name":"example-worker","account_id":"another-account","r2_buckets":[{"binding":"CACHE"}],"durable_objects":{"bindings":[{"name":"STATE"}]}}'); spawnSync('git',['add','wrangler.jsonc'],{cwd:worker}); spawnSync('git',['commit','-qm','declare conflicting account'],{cwd:worker}); const conflictingRevision=spawnSync('git',['rev-parse','HEAD'],{cwd:worker,encoding:'utf8'}).stdout.trim(); const mismatch=await run({...base,repository:{...base.repository,revision:conflictingRevision}}); assert.equal(mismatch.status,1); assert.equal(outputResult(mismatch.stdout).failure.code,'account_target_mismatch');

rmSync(root,{recursive:true,force:true}); }
async function run(contract, environment={}) { writeFileSync(calls,'');writeFileSync(state,'0');const path=join(root,'contract.json');writeFileSync(path,JSON.stringify(contract));const throughHomeboy=process.env.HOMEBOY_EXTENSION_RUN==='1';const command=throughHomeboy?'homeboy':process.execPath;const args=throughHomeboy?['extension','run','cloudflare-workers','--','--contract',path]:[script,'--contract',path];return new Promise((resolveRun,reject)=>{const child=spawn(command,args,{env:{...process.env,CALLS:calls,STATE:state,TEST_SECRET:'never-log-this-value',SECRET_VALUE:'never-log-this-value',...environment},stdio:['ignore','pipe','pipe']});let stdout='';let stderr='';child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.once('error',reject);child.once('close',status=>resolveRun({status,stdout,stderr}));}); }
function listen(responses) { let requests=0; const server=http.createServer((_q,res)=>{const response=responses[Math.min(requests++,responses.length-1)];res.statusCode=response.status;res.end(response.body);});return new Promise((resolveListen,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolveListen({server,port:server.address().port}));}); }
function outputResult(stdout) { const value=JSON.parse(stdout); return value.schema==='homeboy/command-result/v3' ? JSON.parse(value.data.output) : value; }
function deploymentCalls() { return readFileSync(calls,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse).filter((args)=>args[0]==='deploy'&&!args.includes('--dry-run')).length; }
