'use strict';

/**
 * Internal dependencies
 */
const staticVisualParity = require('./lib/static-visual-parity');

module.exports = {
	...require('./lib/admin-page-scenarios'),
	...require('./lib/wordpress-bootstrap-timeline'),
	...require('./lib/request-profiler'),
	...require('./lib/rest-db-query-profiler'),
	...require('./lib/db-inventory'),
	...require('./lib/browser-request-coverage'),
	...require('./lib/full-surface-coverage'),
	...require('./lib/external-http-guardrail'),
	...require('./lib/page-profiler'),
	...require('./lib/rest-route-matrix'),
	...require('./lib/wordpress-route-latency'),
	...require('./lib/block-quality'),
	...require('./lib/materialized-site-quality'),
	...require('./lib/editor-canvas-probes'),
	...require('./lib/fidelity-comparison'),
	...require('./lib/timing-correlator'),
	...require('./lib/helper-manifest'),
	...require('./lib/wordpress-helper-consumer'),
	...require('./lib/fixture-setup'),
	...require('./lib/webperf-evidence-summary'),
	...require('./lib/benchmark-matrix-report'),
	...require('./lib/static-site-fanout-adapter'),
	...require('./lib/audit-fanout-runtime-provider'),
	...require('./lib/agent-terminal-actions'),
	...require('./lib/agent-task-runner-spec'),
	...require('./lib/wp-codebox-apply-adapter'),
	...require('./lib/codebox-provider-adapter'),
	...require('./lib/wp-codebox-recipe-helper'),
	...require('./lib/wp-codebox-fuzz-plan'),
	...require('./lib/wp-codebox-artifacts'),
	...require('./lib/wordpress-workload-profile'),
	buildStaticVisualParityRecipe: staticVisualParity.buildStaticVisualParityRecipe,
	createStaticServer: staticVisualParity.createStaticServer,
	normalizeStaticVisualParityArtifacts: staticVisualParity.normalizeStaticVisualParityArtifacts,
	runStaticVisualParity: staticVisualParity.runStaticVisualParity,
	writeStaticVisualParitySummary: staticVisualParity.writeStaticVisualParitySummary,
	...require('./lib/wordpress-runtime-task-planner'),
	wpCodebox: {
		...require('./lib/codebox-memory-report'),
		...require('./lib/wp-codebox-apply-adapter'),
		...require('./lib/codebox-provider-adapter'),
		...require('./lib/wp-codebox-recipe-helper'),
		...require('./lib/wp-codebox-fuzz-plan'),
		...require('./lib/wp-codebox-artifacts'),
		buildWpCodeboxStaticVisualParityRecipe: staticVisualParity.buildWpCodeboxStaticVisualParityRecipe,
		createWpCodeboxStaticVisualParityRuntimeProvider: staticVisualParity.createWpCodeboxStaticVisualParityRuntimeProvider,
		normalizeWpCodeboxStaticVisualParityArtifacts: staticVisualParity.normalizeWpCodeboxStaticVisualParityArtifacts,
		runWpCodeboxStaticVisualParity: staticVisualParity.runWpCodeboxStaticVisualParity,
		writeWpCodeboxStaticVisualParitySummary: staticVisualParity.writeWpCodeboxStaticVisualParitySummary,
	},
};
