'use strict';

/**
 * Internal dependencies
 */
const staticVisualParity = require('./lib/static-visual-parity');
const wordpressVisualAttribution = require('./lib/wordpress-visual-attribution');

module.exports = {
	...require('./lib/admin-page-scenarios'),
	...require('./lib/admin-page-fuzz-surfaces'),
	...require('./lib/wordpress-admin-form-action-surfaces'),
	...require('./lib/wordpress-bootstrap-timeline'),
	...require('./lib/request-profiler'),
	...require('./lib/rest-db-query-profiler'),
	...require('./lib/wordpress-rest-db-query-profile-preset'),
	...require('./lib/db-inventory'),
	...require('./lib/wordpress-discovery-inventory'),
	...require('./lib/browser-request-coverage'),
	...require('./lib/full-surface-coverage'),
	...require('./lib/external-http-guardrail'),
	...require('./lib/page-profiler'),
	...require('./lib/ajax-action-surface'),
	...require('./lib/rest-route-matrix'),
	...require('./lib/wordpress-rest-route-discovery'),
	...require('./lib/wordpress-rest-fuzz-surface-discovery'),
	...require('./lib/wordpress-route-latency'),
	...require('./lib/block-quality'),
	...require('./lib/materialized-site-quality'),
	...require('./lib/editor-canvas-probes'),
	...require('./lib/fidelity-comparison'),
	...require('./lib/timing-correlator'),
	...require('./lib/helper-manifest'),
	...require('./lib/wordpress-helper-consumer'),
	...require('./lib/fixture-setup'),
	...require('./lib/webperf-evidence-summary'),
	...require('./lib/benchmark-matrix-report'),
	...require('./lib/fixture-workload-matrix'),
	...require('./lib/agent-terminal-actions'),
	...require('./lib/agent-task-runner-spec'),
	...require('./lib/wordpress-workload-profile'),
	...require('./lib/wordpress-workload-scale-profile'),
	...require('./lib/wordpress-fuzz-manifest'),
	...require('./lib/wordpress-fuzz-command-manifest'),
	...require('./lib/wordpress-fuzz-runtime-capabilities'),
	...require('./lib/wordpress-surface-types'),
	...require('./lib/wordpress-surface-family-contracts'),
	...require('./lib/wordpress-hook-surface-discovery'),
	...require('./lib/wordpress-fuzz-schemas'),
	...require('./lib/wordpress-generic-fuzz-primitives'),
	...require('./lib/wordpress-fuzz-mutation-lifecycle'),
	...require('./lib/wordpress-performance-observation-aggregate'),
	...require('./lib/wordpress-runtime-surface-discovery'),
	...require('./lib/wordpress-live-surface-discovery'),
	...require('./lib/homeboy-public-contract-evidence-adapter'),
	...require('./lib/woocommerce-public-contract-discovery'),
	...require('./lib/wordpress-fuzz-plan-from-surfaces'),
	...require('./lib/wordpress-fuzz-campaign'),
	...require('./lib/wordpress-dependency-materialization-recipes'),
	...require('./lib/wordpress-fuzz-runner'),
	...require('./lib/wordpress-fuzz-runtime-task'),
	...require('./lib/wordpress-fuzz-runtime-workload-operations'),
	buildStaticVisualParityRecipe: staticVisualParity.buildStaticVisualParityRecipe,
	createStaticServer: staticVisualParity.createStaticServer,
	normalizeStaticVisualParityArtifacts: staticVisualParity.normalizeStaticVisualParityArtifacts,
	runStaticVisualParity: staticVisualParity.runStaticVisualParity,
	writeStaticVisualParitySummary: staticVisualParity.writeStaticVisualParitySummary,
	normalizeWordPressVisualAttribution: wordpressVisualAttribution.normalizeWordPressVisualAttribution,
	...require('./lib/wordpress-runtime-task-planner'),
	wpCodebox: {
		...require('./lib/codebox-memory-report'),
		...require('./lib/wp-codebox-apply-adapter'),
		...require('./lib/codebox-client'),
		...require('./lib/wp-codebox-recipe-helper'),
		...require('./lib/wp-codebox-resolver'),
		...require('./lib/wp-codebox-fuzz-plan'),
		...require('./lib/wp-codebox-artifacts'),
		// The canonical WP Codebox contract modules resolve an installed WP
		// Codebox runtime, so they stay behind their own package export paths
		// rather than loading whenever this extension is imported.
		...require('./lib/wp-codebox-fuzz-run'),
		buildWpCodeboxStaticVisualParityRecipe: staticVisualParity.buildWpCodeboxStaticVisualParityRecipe,
		createWpCodeboxStaticVisualParityRuntimeProvider: staticVisualParity.createWpCodeboxStaticVisualParityRuntimeProvider,
		normalizeWpCodeboxStaticVisualParityArtifacts: staticVisualParity.normalizeWpCodeboxStaticVisualParityArtifacts,
		runWpCodeboxStaticVisualParity: staticVisualParity.runWpCodeboxStaticVisualParity,
		writeWpCodeboxStaticVisualParitySummary: staticVisualParity.writeWpCodeboxStaticVisualParitySummary,
		normalizeWordPressVisualAttribution: wordpressVisualAttribution.normalizeWordPressVisualAttribution,
	},
};
