#!/bin/bash
set -euo pipefail

DB_TYPE="$1"
ABSPATH="$2"
MODULE_PATH="${3:-$(pwd)}"

echo "Generating wp-config.php for $DB_TYPE..."

# Copy SQLite driver to wp-content location
mkdir -p "$ABSPATH/wp-content"
if [ -f "${MODULE_PATH}/sqlitedb/db.php" ]; then
    cp "${MODULE_PATH}/sqlitedb/db.php" "$ABSPATH/wp-content/"
fi

if [ "$DB_TYPE" = "sqlite" ]; then
    cat > "$ABSPATH/wp-config.php" <<'PHP'
<?php
define('DB_NAME', ':memory:');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

$table_prefix = 'wptests_';

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', false);
define('WP_DEBUG_DISPLAY', false);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

// Activate SQLite database driver
require_once ABSPATH . 'wp-content/db.php';
PHP
else
    MYSQL_HOST="$4"
    MYSQL_DATABASE="$5"
    MYSQL_USER="$6"
    MYSQL_PASSWORD="$7"

    cat > "$ABSPATH/wp-config.php" <<PHP
<?php
define('DB_NAME', '$MYSQL_DATABASE');
define('DB_USER', '$MYSQL_USER');
define('DB_PASSWORD', '$MYSQL_PASSWORD');
define('DB_HOST', '$MYSQL_HOST');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

\$table_prefix = 'wptests_';

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', false);
define('WP_DEBUG_DISPLAY', false);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}
PHP
fi

echo "wp-config.php generated"

# Generate wp-tests-config.php in the cache directory (parent of WordPress)
# This is used by wp-phpunit via WP_PHPUNIT__TESTS_CONFIG env var
CONFIG_DIR="$(dirname "$ABSPATH")"
cat > "$CONFIG_DIR/wp-tests-config.php" <<PHP
<?php
// Generated by Homeboy WordPress module test runner.
\$table_prefix = 'wptests_';

if ( ! defined( 'DB_NAME' ) ) define('DB_NAME', ':memory:');
if ( ! defined( 'DB_USER' ) ) define('DB_USER', 'root');
if ( ! defined( 'DB_PASSWORD' ) ) define('DB_PASSWORD', '');
if ( ! defined( 'DB_HOST' ) ) define('DB_HOST', 'localhost');
if ( ! defined( 'DB_CHARSET' ) ) define('DB_CHARSET', 'utf8');

if ( ! defined( 'WP_TESTS_DOMAIN' ) ) define('WP_TESTS_DOMAIN', 'example.org');
if ( ! defined( 'WP_TESTS_EMAIL' ) ) define('WP_TESTS_EMAIL', 'admin@example.org');
if ( ! defined( 'WP_TESTS_TITLE' ) ) define('WP_TESTS_TITLE', 'Test Blog');
if ( ! defined( 'WP_PHP_BINARY' ) ) define('WP_PHP_BINARY', 'php');

// ABSPATH points to the cached WordPress installation
if ( ! defined( 'ABSPATH' ) ) define('ABSPATH', '${ABSPATH}/');
PHP

echo "wp-tests-config.php generated"
