#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTENSION_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEPENDENCY_HELPER="${EXTENSION_DIR}/scripts/lib/validation-dependencies.sh"

# shellcheck source=../scripts/lib/validation-dependencies.sh
source "$DEPENDENCY_HELPER"

TMP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/homeboy-prepared-dep-cache-smoke.XXXXXX")
trap 'rm -rf "$TMP_ROOT"' EXIT

SOURCE_REPO="${TMP_ROOT}/source-repo"
PLUGIN_DIR="${SOURCE_REPO}/plugins/generic-dep"
CACHE_DIR="${TMP_ROOT}/cache"
CALLS_FILE="${TMP_ROOT}/composer-calls.txt"
FAKE_BIN="${TMP_ROOT}/bin"

mkdir -p "$PLUGIN_DIR" "$CACHE_DIR" "$FAKE_BIN"

cat > "${PLUGIN_DIR}/generic-dep.php" <<'PHP'
<?php
/**
 * Plugin Name: Generic Dependency
 */
PHP

cat > "${PLUGIN_DIR}/composer.json" <<'JSON'
{"name":"fixture/generic-dep","autoload":{"psr-4":{"Fixture\\GenericDep\\":"src/"}}}
JSON

cat > "${PLUGIN_DIR}/composer.lock" <<'JSON'
{"packages":[],"packages-dev":[]}
JSON

cat > "${FAKE_BIN}/composer" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail

working_dir=""
for arg in "$@"; do
    case "$arg" in
        --working-dir=*)
            working_dir="${arg#--working-dir=}"
            ;;
    esac
done

if [ -z "$working_dir" ]; then
    working_dir="$PWD"
fi

printf '%s\n' "$working_dir" >> "$COMPOSER_CALLS_FILE"
mkdir -p "${working_dir}/vendor"
printf '%s\n' '<?php // generated by fake composer' > "${working_dir}/vendor/autoload.php"
BASH
chmod +x "${FAKE_BIN}/composer"

git -C "$SOURCE_REPO" init --quiet
git -C "$SOURCE_REPO" add .
git -C "$SOURCE_REPO" -c user.name='Homeboy Smoke' -c user.email='homeboy-smoke@example.com' commit --quiet -m 'Initial dependency fixture'

export PATH="${FAKE_BIN}:${PATH}"
export COMPOSER_CALLS_FILE="$CALLS_FILE"
export HOMEBOY_CACHE_DIR="$CACHE_DIR"

first_prepared=$(homeboy_prepare_validation_dependency_for_wp_codebox_bench "$PLUGIN_DIR" "${TMP_ROOT}/artifacts-one")
second_prepared=$(homeboy_prepare_validation_dependency_for_wp_codebox_bench "$PLUGIN_DIR" "${TMP_ROOT}/artifacts-two")

if [ "$first_prepared" != "$second_prepared" ]; then
    echo "ERROR: expected cache hit to return the same prepared dependency path." >&2
    exit 1
fi

if [ -d "${PLUGIN_DIR}/vendor" ]; then
    echo "ERROR: source dependency was mutated by Composer prepare." >&2
    exit 1
fi

call_count=$(wc -l < "$CALLS_FILE" | tr -d '[:space:]')
if [ "$call_count" != "1" ]; then
    echo "ERROR: expected one Composer invocation after cache hit, got ${call_count}." >&2
    exit 1
fi

if ! jq -e 'length == 1 and .[0].cache_status == "hit" and (.[0].prepared_path | type == "string")' "${TMP_ROOT}/artifacts-two/prepared-bench-dependencies.json" >/dev/null; then
    echo "ERROR: expected cache hit metadata in artifacts-two." >&2
    exit 1
fi

cat > "${PLUGIN_DIR}/composer.lock" <<'JSON'
{"packages":[{"name":"fixture/changed","version":"1.0.0"}],"packages-dev":[]}
JSON

lock_changed_prepared=$(homeboy_prepare_validation_dependency_for_wp_codebox_bench "$PLUGIN_DIR" "${TMP_ROOT}/artifacts-three")
if [ "$lock_changed_prepared" = "$first_prepared" ]; then
    echo "ERROR: expected composer.lock change to invalidate the prepared dependency cache." >&2
    exit 1
fi

call_count=$(wc -l < "$CALLS_FILE" | tr -d '[:space:]')
if [ "$call_count" != "2" ]; then
    echo "ERROR: expected Composer to run after composer.lock invalidation, got ${call_count}." >&2
    exit 1
fi

git -C "$SOURCE_REPO" add plugins/generic-dep/composer.lock
git -C "$SOURCE_REPO" -c user.name='Homeboy Smoke' -c user.email='homeboy-smoke@example.com' commit --quiet -m 'Change dependency lock'

sha_changed_prepared=$(homeboy_prepare_validation_dependency_for_wp_codebox_bench "$PLUGIN_DIR" "${TMP_ROOT}/artifacts-four")
if [ "$sha_changed_prepared" = "$lock_changed_prepared" ]; then
    echo "ERROR: expected git revision change to invalidate the prepared dependency cache." >&2
    exit 1
fi

call_count=$(wc -l < "$CALLS_FILE" | tr -d '[:space:]')
if [ "$call_count" != "3" ]; then
    echo "ERROR: expected Composer to run after git revision invalidation, got ${call_count}." >&2
    exit 1
fi

if [ ! -f "${sha_changed_prepared}/vendor/autoload.php" ]; then
    echo "ERROR: prepared dependency is missing Composer autoload." >&2
    exit 1
fi

if ! jq -e 'length == 1 and .[0].cache_status == "miss" and (.[0].cache_key | type == "string")' "${TMP_ROOT}/artifacts-four/prepared-bench-dependencies.json" >/dev/null; then
    echo "ERROR: expected cache miss metadata in artifacts-four." >&2
    exit 1
fi

echo "prepared bench dependency cache smoke passed"
